# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: "windows-latest"

steps:
- task: TerraformTool@0
  inputs:
    version: '1.0.1'
 
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'NewTestConnection-VSE-efaa'
    backendAzureRmResourceGroupName: 'VYDND-RG'
    backendAzureRmStorageAccountName: 'terraformbackend742'
    backendAzureRmContainerName: 'tstate'
    backendAzureRmKey: 'tf/terraform.tfstate'
 
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'NewTestConnection-VSE-efaa'
 