# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTool@0
  inputs:
    version: '0.11.8'


- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'terraformbackend742'
    backendServiceArm: 'NewTestConnection-VSE-efaa'
    backendAzureRmResourceGroupName: 'VYDND-RG'
    backendAzureRmStorageAccountName: 'terraformbackend742'
    backendAzureRmContainerName: 'terraformstatefiles'
    backendAzureRmKey: 'tf/terraform.tfstate1'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'NewTestConnection-VSE-efaa'
  
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'NewTestConnection-VSE-efaa'
